### ISSUE TITLE
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[MatchError: javascripts/titaniumcore/packages.js (of class java.lang.String)]]

### ISSUE THREAD

**Issue by Bhagyashree-B** [shreyaspurohit/SRPScala#2]
Hi,
I was trying SRPScala's srp implementation in my application but while including web/js files, got an Execution  exception 
`play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[MatchError: javascripts/titaniumcore/packages.js (of class java.lang.String)]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
Caused by: scala.MatchError: javascripts/titaniumcore/packages.js (of class java.lang.String)
        at controllers.ReverseAssets.at(ReverseRoutes.scala:25)
        at views.html.index_Scope0$index.apply(index.template.scala:51)
        at controllers.Main$$anonfun$index$1.apply(Main.scala:15)
        at controllers.Main$$anonfun$index$1.apply(Main.scala:15)
        at play.api.mvc.ActionBuilder$$anonfun$apply$14.apply(Action.scala:403)
        at play.api.mvc.ActionBuilder$$anonfun$apply$14.apply(Action.scala:403)
        at play.api.mvc.ActionBuilder$$anonfun$apply$13.apply(Action.scala:371)
        at play.api.mvc.ActionBuilder$$anonfun$apply$13.apply(Action.scala:370)
        at play.api.mvc.Action$.invokeBlock(Action.scala:498)
        at play.api.mvc.Action$.invokeBlock(Action.scala:495)
`
Could you please help me with this?

**Comment by shreyaspurohit** [comment]
This has nothing to with lib. The play server is not able to find your assets.
```
scala.MatchError: javascripts/titaniumcore/packages.js (of class java.lang.String) at controllers.ReverseAssets.at(ReverseRoutes.scala:25)
```
